name: bitsgap
description: Authentication.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  mobx: 2.1.4
  flutter_mobx: 2.0.6+5

  # storage
  shared_preferences: 2.1.0

  # di
  get_it: 7.3.0

  cupertino_icons: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.3
  mobx_codegen: 2.2.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - res/images/

  fonts:
    - family: TTNormsPro
      fonts:
        - asset: res/fonts/TTNormsPro-Regular.ttf
          weight: 400
        - asset: res/fonts/TTNormsPro-Medium.ttf
          weight: 500